Completed the weather app template code
TheGuyDangerous/MernStack pull request #10
Opened 2024-01-21 12:09 UTC by bhukya-sainaveen

# The weather app template
### Tech Stack - React, Bootstrap, API Calls
The weather app uses [OpenWeatherMap](https://openweathermap.org/api) API key to describe the current weather.
The API key can be set in the config.js file.

2024-01-22 19:56 UTC, TheGuyDangerous requested changes
Please include your ```weather-app``` project in the ```index.html``` file and make sure it works properly, when opened on a local host server, without any background server needing to be opened.

2024-01-22 19:56 UTC, TheGuyDangerous commented on React/weather-app/.gitignore
Make sure to not include ```.gitignore``` files while creating a PR

2024-01-23 08:18 UTC, bhukya-sainaveen reviewed
Modified the index.html to support the weather app and also tested the website using the local server to see whether the code was working without any background server needing to be opened.

2024-01-25 14:10 UTC, TheGuyDangerous approved these changes
All  good ✅

2024-01-25 14:11 UTC, merged